<?php

class Core_Countries {

	/**
	 * Make changes to the database.
	 *
	 * @return void
	 */
	public function up()
	{
		Schema::create('core_countries', function($table){
			$table->increments('id')->unsigned();
			$table->string('code',2)->unique();
			$table->string('name');
			$table->boolean('active')->nullable();
		});
		DB::table('core_countries')->insert(array('code'=>'AF','name'=>'Afghanistan'));
		DB::table('core_countries')->insert(array('code'=>'AL','name'=>'Albania'));
		DB::table('core_countries')->insert(array('code'=>'DZ','name'=>'Algeria'));
		DB::table('core_countries')->insert(array('code'=>'AS','name'=>'American Samoa'));
		DB::table('core_countries')->insert(array('code'=>'AD','name'=>'Andorra'));
		DB::table('core_countries')->insert(array('code'=>'AO','name'=>'Angola'));
		DB::table('core_countries')->insert(array('code'=>'AI','name'=>'Anguilla'));
		DB::table('core_countries')->insert(array('code'=>'AQ','name'=>'Antarctica'));
		DB::table('core_countries')->insert(array('code'=>'AG','name'=>'Antigua and Barbuda'));
		DB::table('core_countries')->insert(array('code'=>'AR','name'=>'Argentina'));
		DB::table('core_countries')->insert(array('code'=>'AM','name'=>'Armenia'));
		DB::table('core_countries')->insert(array('code'=>'AW','name'=>'Aruba'));
		DB::table('core_countries')->insert(array('code'=>'AU','name'=>'Australia'));
		DB::table('core_countries')->insert(array('code'=>'AT','name'=>'Austria'));
		DB::table('core_countries')->insert(array('code'=>'AZ','name'=>'Azerbaijan'));
		DB::table('core_countries')->insert(array('code'=>'BS','name'=>'Bahamas'));
		DB::table('core_countries')->insert(array('code'=>'BH','name'=>'Bahrain'));
		DB::table('core_countries')->insert(array('code'=>'BD','name'=>'Bangladesh'));
		DB::table('core_countries')->insert(array('code'=>'BB','name'=>'Barbados'));
		DB::table('core_countries')->insert(array('code'=>'BY','name'=>'Belarus'));
		DB::table('core_countries')->insert(array('code'=>'BE','name'=>'Belgium'));
		DB::table('core_countries')->insert(array('code'=>'BZ','name'=>'Belize'));
		DB::table('core_countries')->insert(array('code'=>'BJ','name'=>'Benin'));
		DB::table('core_countries')->insert(array('code'=>'BM','name'=>'Bermuda'));
		DB::table('core_countries')->insert(array('code'=>'BT','name'=>'Bhutan'));
		DB::table('core_countries')->insert(array('code'=>'BO','name'=>'Bolivia'));
		DB::table('core_countries')->insert(array('code'=>'BA','name'=>'Bosnia and Herzegovina'));
		DB::table('core_countries')->insert(array('code'=>'BW','name'=>'Botswana'));
		DB::table('core_countries')->insert(array('code'=>'BV','name'=>'Bouvet Island'));
		DB::table('core_countries')->insert(array('code'=>'BR','name'=>'Brazil'));
		DB::table('core_countries')->insert(array('code'=>'IO','name'=>'British Indian Ocean Territory'));
		DB::table('core_countries')->insert(array('code'=>'VG','name'=>'British Virgin Islands'));
		DB::table('core_countries')->insert(array('code'=>'BN','name'=>'Brunei Darussalam'));
		DB::table('core_countries')->insert(array('code'=>'BG','name'=>'Bulgaria'));
		DB::table('core_countries')->insert(array('code'=>'BF','name'=>'Burkina Faso'));
		DB::table('core_countries')->insert(array('code'=>'BI','name'=>'Burundi'));
		DB::table('core_countries')->insert(array('code'=>'KH','name'=>'Cambodia'));
		DB::table('core_countries')->insert(array('code'=>'CM','name'=>'Cameroon'));
		DB::table('core_countries')->insert(array('code'=>'CA','name'=>'Canada'));
		DB::table('core_countries')->insert(array('code'=>'CV','name'=>'Cape Verde'));
		DB::table('core_countries')->insert(array('code'=>'KY','name'=>'Cayman Islands'));
		DB::table('core_countries')->insert(array('code'=>'CF','name'=>'Central African Republic'));
		DB::table('core_countries')->insert(array('code'=>'TD','name'=>'Chad'));
		DB::table('core_countries')->insert(array('code'=>'CL','name'=>'Chile'));
		DB::table('core_countries')->insert(array('code'=>'CN','name'=>'China'));
		DB::table('core_countries')->insert(array('code'=>'CX','name'=>'Christmas Island'));
		DB::table('core_countries')->insert(array('code'=>'CC','name'=>'Cocos'));
		DB::table('core_countries')->insert(array('code'=>'CO','name'=>'Colombia'));
		DB::table('core_countries')->insert(array('code'=>'KM','name'=>'Comoros'));
		DB::table('core_countries')->insert(array('code'=>'CD','name'=>'Congo'));
		DB::table('core_countries')->insert(array('code'=>'CG','name'=>'Congo'));
		DB::table('core_countries')->insert(array('code'=>'CK','name'=>'Cook Islands'));
		DB::table('core_countries')->insert(array('code'=>'CR','name'=>'Costa Rica'));
		DB::table('core_countries')->insert(array('code'=>'CI','name'=>'Cote D\'Ivoire'));
		DB::table('core_countries')->insert(array('code'=>'CU','name'=>'Cuba'));
		DB::table('core_countries')->insert(array('code'=>'CY','name'=>'Cyprus'));
		DB::table('core_countries')->insert(array('code'=>'CZ','name'=>'Czech Republic'));
		DB::table('core_countries')->insert(array('code'=>'DK','name'=>'Denmark'));
		DB::table('core_countries')->insert(array('code'=>'DJ','name'=>'Djibouti'));
		DB::table('core_countries')->insert(array('code'=>'DM','name'=>'Dominica'));
		DB::table('core_countries')->insert(array('code'=>'DO','name'=>'Dominican Republic'));
		DB::table('core_countries')->insert(array('code'=>'EC','name'=>'Ecuador'));
		DB::table('core_countries')->insert(array('code'=>'EG','name'=>'Egypt'));
		DB::table('core_countries')->insert(array('code'=>'SV','name'=>'El Salvador'));
		DB::table('core_countries')->insert(array('code'=>'GQ','name'=>'Equatorial Guinea'));
		DB::table('core_countries')->insert(array('code'=>'ER','name'=>'Eritrea'));
		DB::table('core_countries')->insert(array('code'=>'EE','name'=>'Estonia'));
		DB::table('core_countries')->insert(array('code'=>'ET','name'=>'Ethiopia'));
		DB::table('core_countries')->insert(array('code'=>'FO','name'=>'Faeroe Islands'));
		DB::table('core_countries')->insert(array('code'=>'FK','name'=>'Falkland Islands'));
		DB::table('core_countries')->insert(array('code'=>'FJ','name'=>'Fiji'));
		DB::table('core_countries')->insert(array('code'=>'FI','name'=>'Finland'));
		DB::table('core_countries')->insert(array('code'=>'FR','name'=>'France'));
		DB::table('core_countries')->insert(array('code'=>'GF','name'=>'French Guiana'));
		DB::table('core_countries')->insert(array('code'=>'PF','name'=>'French Polynesia'));
		DB::table('core_countries')->insert(array('code'=>'TF','name'=>'French Southern Territories'));
		DB::table('core_countries')->insert(array('code'=>'GA','name'=>'Gabon'));
		DB::table('core_countries')->insert(array('code'=>'GM','name'=>'Gambia'));
		DB::table('core_countries')->insert(array('code'=>'GE','name'=>'Georgia'));
		DB::table('core_countries')->insert(array('code'=>'DE','name'=>'Germany'));
		DB::table('core_countries')->insert(array('code'=>'GH','name'=>'Ghana'));
		DB::table('core_countries')->insert(array('code'=>'GI','name'=>'Gibraltar'));
		DB::table('core_countries')->insert(array('code'=>'GR','name'=>'Greece'));
		DB::table('core_countries')->insert(array('code'=>'GL','name'=>'Greenland'));
		DB::table('core_countries')->insert(array('code'=>'GD','name'=>'Grenada'));
		DB::table('core_countries')->insert(array('code'=>'GP','name'=>'Guadaloupe'));
		DB::table('core_countries')->insert(array('code'=>'GU','name'=>'Guam'));
		DB::table('core_countries')->insert(array('code'=>'GT','name'=>'Guatemala'));
		DB::table('core_countries')->insert(array('code'=>'GN','name'=>'Guinea'));
		DB::table('core_countries')->insert(array('code'=>'GW','name'=>'Guinea-Bissau'));
		DB::table('core_countries')->insert(array('code'=>'GY','name'=>'Guyana'));
		DB::table('core_countries')->insert(array('code'=>'HT','name'=>'Haiti'));
		DB::table('core_countries')->insert(array('code'=>'HM','name'=>'Heard and McDonald Islands'));
		DB::table('core_countries')->insert(array('code'=>'VA','name'=>'Holy See'));
		DB::table('core_countries')->insert(array('code'=>'HN','name'=>'Honduras'));
		DB::table('core_countries')->insert(array('code'=>'HK','name'=>'Hong Kong'));
		DB::table('core_countries')->insert(array('code'=>'HR','name'=>'Hrvatska'));
		DB::table('core_countries')->insert(array('code'=>'HU','name'=>'Hungary'));
		DB::table('core_countries')->insert(array('code'=>'IS','name'=>'Iceland'));
		DB::table('core_countries')->insert(array('code'=>'IN','name'=>'India'));
		DB::table('core_countries')->insert(array('code'=>'ID','name'=>'Indonesia'));
		DB::table('core_countries')->insert(array('code'=>'IR','name'=>'Iran'));
		DB::table('core_countries')->insert(array('code'=>'IQ','name'=>'Iraq'));
		DB::table('core_countries')->insert(array('code'=>'IE','name'=>'Ireland'));
		DB::table('core_countries')->insert(array('code'=>'IL','name'=>'Israel'));
		DB::table('core_countries')->insert(array('code'=>'IT','name'=>'Italy'));
		DB::table('core_countries')->insert(array('code'=>'JM','name'=>'Jamaica'));
		DB::table('core_countries')->insert(array('code'=>'JP','name'=>'Japan'));
		DB::table('core_countries')->insert(array('code'=>'JO','name'=>'Jordan'));
		DB::table('core_countries')->insert(array('code'=>'KZ','name'=>'Kazakhstan'));
		DB::table('core_countries')->insert(array('code'=>'KE','name'=>'Kenya'));
		DB::table('core_countries')->insert(array('code'=>'KI','name'=>'Kiribati'));
		DB::table('core_countries')->insert(array('code'=>'KP','name'=>'Korea'));
		DB::table('core_countries')->insert(array('code'=>'KR','name'=>'Korea'));
		DB::table('core_countries')->insert(array('code'=>'KW','name'=>'Kuwait'));
		DB::table('core_countries')->insert(array('code'=>'KG','name'=>'Kyrgyz Republic'));
		DB::table('core_countries')->insert(array('code'=>'LA','name'=>'Lao People\'s Democratic Republic'));
		DB::table('core_countries')->insert(array('code'=>'LV','name'=>'Latvia'));
		DB::table('core_countries')->insert(array('code'=>'LB','name'=>'Lebanon'));
		DB::table('core_countries')->insert(array('code'=>'LS','name'=>'Lesotho'));
		DB::table('core_countries')->insert(array('code'=>'LR','name'=>'Liberia'));
		DB::table('core_countries')->insert(array('code'=>'LY','name'=>'Libyan Arab Jamahiriya'));
		DB::table('core_countries')->insert(array('code'=>'LI','name'=>'Liechtenstein'));
		DB::table('core_countries')->insert(array('code'=>'LT','name'=>'Lithuania'));
		DB::table('core_countries')->insert(array('code'=>'LU','name'=>'Luxembourg'));
		DB::table('core_countries')->insert(array('code'=>'MO','name'=>'Macao'));
		DB::table('core_countries')->insert(array('code'=>'MK','name'=>'Macedonia'));
		DB::table('core_countries')->insert(array('code'=>'MG','name'=>'Madagascar'));
		DB::table('core_countries')->insert(array('code'=>'MW','name'=>'Malawi'));
		DB::table('core_countries')->insert(array('code'=>'MY','name'=>'Malaysia'));
		DB::table('core_countries')->insert(array('code'=>'MV','name'=>'Maldives'));
		DB::table('core_countries')->insert(array('code'=>'ML','name'=>'Mali'));
		DB::table('core_countries')->insert(array('code'=>'MT','name'=>'Malta'));
		DB::table('core_countries')->insert(array('code'=>'MH','name'=>'Marshall Islands'));
		DB::table('core_countries')->insert(array('code'=>'MQ','name'=>'Martinique'));
		DB::table('core_countries')->insert(array('code'=>'MR','name'=>'Mauritania'));
		DB::table('core_countries')->insert(array('code'=>'MU','name'=>'Mauritius'));
		DB::table('core_countries')->insert(array('code'=>'YT','name'=>'Mayotte'));
		DB::table('core_countries')->insert(array('code'=>'MX','name'=>'Mexico'));
		DB::table('core_countries')->insert(array('code'=>'FM','name'=>'Micronesia'));
		DB::table('core_countries')->insert(array('code'=>'MD','name'=>'Moldova'));
		DB::table('core_countries')->insert(array('code'=>'MC','name'=>'Monaco'));
		DB::table('core_countries')->insert(array('code'=>'MN','name'=>'Mongolia'));
		DB::table('core_countries')->insert(array('code'=>'MS','name'=>'Montserrat'));
		DB::table('core_countries')->insert(array('code'=>'MA','name'=>'Morocco'));
		DB::table('core_countries')->insert(array('code'=>'MZ','name'=>'Mozambique'));
		DB::table('core_countries')->insert(array('code'=>'MM','name'=>'Myanmar'));
		DB::table('core_countries')->insert(array('code'=>'NA','name'=>'Namibia'));
		DB::table('core_countries')->insert(array('code'=>'NR','name'=>'Nauru'));
		DB::table('core_countries')->insert(array('code'=>'NP','name'=>'Nepal'));
		DB::table('core_countries')->insert(array('code'=>'AN','name'=>'Netherlands Antilles'));
		DB::table('core_countries')->insert(array('code'=>'NL','name'=>'Netherlands'));
		DB::table('core_countries')->insert(array('code'=>'NC','name'=>'New Caledonia'));
		DB::table('core_countries')->insert(array('code'=>'NZ','name'=>'New Zealand'));
		DB::table('core_countries')->insert(array('code'=>'NI','name'=>'Nicaragua'));
		DB::table('core_countries')->insert(array('code'=>'NE','name'=>'Niger'));
		DB::table('core_countries')->insert(array('code'=>'NG','name'=>'Nigeria'));
		DB::table('core_countries')->insert(array('code'=>'NU','name'=>'Niue'));
		DB::table('core_countries')->insert(array('code'=>'NF','name'=>'Norfolk Island'));
		DB::table('core_countries')->insert(array('code'=>'MP','name'=>'Northern Mariana Islands'));
		DB::table('core_countries')->insert(array('code'=>'NO','name'=>'Norway'));
		DB::table('core_countries')->insert(array('code'=>'OM','name'=>'Oman'));
		DB::table('core_countries')->insert(array('code'=>'PK','name'=>'Pakistan'));
		DB::table('core_countries')->insert(array('code'=>'PW','name'=>'Palau'));
		DB::table('core_countries')->insert(array('code'=>'PS','name'=>'Palestinian Territory'));
		DB::table('core_countries')->insert(array('code'=>'PA','name'=>'Panama'));
		DB::table('core_countries')->insert(array('code'=>'PG','name'=>'Papua New Guinea'));
		DB::table('core_countries')->insert(array('code'=>'PY','name'=>'Paraguay'));
		DB::table('core_countries')->insert(array('code'=>'PE','name'=>'Peru'));
		DB::table('core_countries')->insert(array('code'=>'PH','name'=>'Philippines'));
		DB::table('core_countries')->insert(array('code'=>'PN','name'=>'Pitcairn Island'));
		DB::table('core_countries')->insert(array('code'=>'PL','name'=>'Poland'));
		DB::table('core_countries')->insert(array('code'=>'PT','name'=>'Portugal'));
		DB::table('core_countries')->insert(array('code'=>'PR','name'=>'Puerto Rico'));
		DB::table('core_countries')->insert(array('code'=>'QA','name'=>'Qatar'));
		DB::table('core_countries')->insert(array('code'=>'RE','name'=>'Reunion'));
		DB::table('core_countries')->insert(array('code'=>'RO','name'=>'Romania'));
		DB::table('core_countries')->insert(array('code'=>'RU','name'=>'Russian Federation'));
		DB::table('core_countries')->insert(array('code'=>'RW','name'=>'Rwanda'));
		DB::table('core_countries')->insert(array('code'=>'SH','name'=>'St. Helena'));
		DB::table('core_countries')->insert(array('code'=>'KN','name'=>'St. Kitts and Nevis'));
		DB::table('core_countries')->insert(array('code'=>'LC','name'=>'St. Lucia'));
		DB::table('core_countries')->insert(array('code'=>'PM','name'=>'St. Pierre and Miquelon'));
		DB::table('core_countries')->insert(array('code'=>'VC','name'=>'St. Vincent and the Grenadines'));
		DB::table('core_countries')->insert(array('code'=>'WS','name'=>'Samoa'));
		DB::table('core_countries')->insert(array('code'=>'SM','name'=>'San Marino'));
		DB::table('core_countries')->insert(array('code'=>'ST','name'=>'Sao Tome and Principe'));
		DB::table('core_countries')->insert(array('code'=>'SA','name'=>'Saudi Arabia'));
		DB::table('core_countries')->insert(array('code'=>'SN','name'=>'Senegal'));
		DB::table('core_countries')->insert(array('code'=>'CS','name'=>'Serbia and Montenegro'));
		DB::table('core_countries')->insert(array('code'=>'SC','name'=>'Seychelles'));
		DB::table('core_countries')->insert(array('code'=>'SL','name'=>'Sierra Leone'));
		DB::table('core_countries')->insert(array('code'=>'SG','name'=>'Singapore'));
		DB::table('core_countries')->insert(array('code'=>'SK','name'=>'Slovakia'));
		DB::table('core_countries')->insert(array('code'=>'SI','name'=>'Slovenia'));
		DB::table('core_countries')->insert(array('code'=>'SB','name'=>'Solomon Islands'));
		DB::table('core_countries')->insert(array('code'=>'SO','name'=>'Somalia'));
		DB::table('core_countries')->insert(array('code'=>'ZA','name'=>'South Africa'));
		DB::table('core_countries')->insert(array('code'=>'GS','name'=>'South Georgia and the South Sandwich Islands'));
		DB::table('core_countries')->insert(array('code'=>'ES','name'=>'Spain'));
		DB::table('core_countries')->insert(array('code'=>'LK','name'=>'Sri Lanka'));
		DB::table('core_countries')->insert(array('code'=>'SD','name'=>'Sudan'));
		DB::table('core_countries')->insert(array('code'=>'SR','name'=>'Suriname'));
		DB::table('core_countries')->insert(array('code'=>'SJ','name'=>'Svalbard & Jan Mayen Islands'));
		DB::table('core_countries')->insert(array('code'=>'SZ','name'=>'Swaziland'));
		DB::table('core_countries')->insert(array('code'=>'SE','name'=>'Sweden'));
		DB::table('core_countries')->insert(array('code'=>'CH','name'=>'Switzerland'));
		DB::table('core_countries')->insert(array('code'=>'SY','name'=>'Syrian Arab Republic'));
		DB::table('core_countries')->insert(array('code'=>'TW','name'=>'Taiwan'));
		DB::table('core_countries')->insert(array('code'=>'TJ','name'=>'Tajikistan'));
		DB::table('core_countries')->insert(array('code'=>'TZ','name'=>'Tanzania'));
		DB::table('core_countries')->insert(array('code'=>'TH','name'=>'Thailand'));
		DB::table('core_countries')->insert(array('code'=>'TL','name'=>'Timor-Leste'));
		DB::table('core_countries')->insert(array('code'=>'TG','name'=>'Togo'));
		DB::table('core_countries')->insert(array('code'=>'TK','name'=>'Tokelau'));
		DB::table('core_countries')->insert(array('code'=>'TO','name'=>'Tonga'));
		DB::table('core_countries')->insert(array('code'=>'TT','name'=>'Trinidad and Tobago'));
		DB::table('core_countries')->insert(array('code'=>'TN','name'=>'Tunisia'));
		DB::table('core_countries')->insert(array('code'=>'TR','name'=>'Turkey'));
		DB::table('core_countries')->insert(array('code'=>'TM','name'=>'Turkmenistan'));
		DB::table('core_countries')->insert(array('code'=>'TC','name'=>'Turks and Caicos Islands'));
		DB::table('core_countries')->insert(array('code'=>'TV','name'=>'Tuvalu'));
		DB::table('core_countries')->insert(array('code'=>'VI','name'=>'US Virgin Islands'));
		DB::table('core_countries')->insert(array('code'=>'UG','name'=>'Uganda'));
		DB::table('core_countries')->insert(array('code'=>'UA','name'=>'Ukraine'));
		DB::table('core_countries')->insert(array('code'=>'AE','name'=>'United Arab Emirates'));
		DB::table('core_countries')->insert(array('code'=>'GB','name'=>'United Kingdom of Great Britain & N. Ireland'));
		DB::table('core_countries')->insert(array('code'=>'UM','name'=>'United States Minor Outlying Islands'));
		DB::table('core_countries')->insert(array('code'=>'US','name'=>'United States of America'));
		DB::table('core_countries')->insert(array('code'=>'UY','name'=>'Uruguay'));
		DB::table('core_countries')->insert(array('code'=>'UZ','name'=>'Uzbekistan'));
		DB::table('core_countries')->insert(array('code'=>'VU','name'=>'Vanuatu'));
		DB::table('core_countries')->insert(array('code'=>'VE','name'=>'Venezuela'));
		DB::table('core_countries')->insert(array('code'=>'VN','name'=>'Viet Nam'));
		DB::table('core_countries')->insert(array('code'=>'WF','name'=>'Wallis and Futuna Islands'));
		DB::table('core_countries')->insert(array('code'=>'EH','name'=>'Western Sahara'));
		DB::table('core_countries')->insert(array('code'=>'YE','name'=>'Yemen'));
		DB::table('core_countries')->insert(array('code'=>'ZM','name'=>'Zambia'));
		DB::table('core_countries')->insert(array('code'=>'ZW','name'=>'Zimbabwe'));
	}

	/**
	 * Revert the changes to the database.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::drop('core_countries');
	}

}